name: Deploy to VPS

on:
  push:
    branches: [main]
    paths:
      - 'www/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "www/*"
          target: "/var/www/apps/lisear"
          strip_components: 1
